### PR TITLE
Add python installation instructions and initial requirements file

### PR DESCRIPTION
**Pull request by davidabrahams**
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/1)

### CODE REVIEW

**Review by altodyte — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/1)* status: altodyte must resolve 1 discussion (waiting on @davidabrahams)

___
*[python/ball.py, line 9 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/1#-Ln_Q7VqBXTli9A-g0XF:-Ln_Q7VqBXTli9A-g0XG:b1fy41i) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/0f9b8bfc7833b6908f2dca6331215ac649234625/python/ball.py#L9)):*
> ```Python
> 
> l: List[int] = []
> ball = Ball(1, 2)
> ```

I think we should probably break unit tests / example code out into a separate file

**Review by davidabrahams — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/1)* status: billmwong must review 3 files, shanek21 must review 3 files, altodyte must review 3 files, altodyte must resolve 1 discussion (waiting on @altodyte)

___
*[python/ball.py, line 9 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/1#-Ln_Q7VqBXTli9A-g0XF:-Ln_ScPZ1IbOx1dn9z4w:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/0f9b8bfc7833b6908f2dca6331215ac649234625/python/ball.py#L9)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

I think we should probably break unit tests / example code out into a separate file
</blockquote></details>

Done.

**Review by altodyte — APPROVED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/1)* status: billmwong must review 1 file, shanek21 must review 1 file, altodyte must review 1 file, altodyte must resolve 1 discussion (waiting on @altodyte and @davidabrahams)

___
*[python/ball.py, line 4 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/1#-Ln_VUtO0QV-EcHaJx_E:-Ln_VUtO0QV-EcHaJx_F:bfbk03p) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/c9acdfe510b2d75bd21c0293128020d7da43e4e7/python/ball.py#L4)):*
> ```Python
>     def __init__(self, x: int, y: int) -> None:
>         self.x = x
>         self.y = y
> ```

It might be worth adding some other members now that we know we'll need, but that can be in a follow-up PR.

**Review by altodyte — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/1)* status: altodyte must resolve 1 discussion (waiting on @davidabrahams)

**Review by altodyte — COMMENTED** [review]
:dango: :dango: help I have no idea how reviewable works

> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/1#-:-Ln_Vrjd12_uGzxclZcO:b-brpych)* status: altodyte must resolve 1 discussion (waiting on @davidabrahams)

**Review by davidabrahams — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/1)* status: altodyte must resolve 1 discussion (waiting on @altodyte)

___
*[python/ball.py, line 4 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/1#-Ln_VUtO0QV-EcHaJx_E:-Ln_Xpol5xlwTCHjTGTE:b1nb94x) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/c9acdfe510b2d75bd21c0293128020d7da43e4e7/python/ball.py#L4)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

It might be worth adding some other members now that we know we'll need, but that can be in a follow-up PR.
</blockquote></details>

Done. Yeah my goal was to get some code that we could run

**Review by altodyte — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
