### PR TITLE
Make main executable

### LINKED ISSUE #17: main.py not executable

### PR DESCRIPTION
**Pull request by billmwong**
Closes #17

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/18)

### CODE REVIEW

**Review by altodyte — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/18)* status: davidabrahams must review 1 file, shanekelly must review 1 file, altodyte must review 1 file, altodyte must resolve 1 discussion (waiting on @altodyte, @billmwong, @davidabrahams, and @shanekelly)

___
*[python/main.py, line 1 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/18#-Lo8z78dAFYv06IIE5sU:-Lo8z78dAFYv06IIE5sV:bxx7uea) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f9700bdd6c45857e555f6571e28a41de24728f6/python/main.py#L1)):*
> ```Python
> #!/usr/bin/env python
> ```

It feels like it is wrong that this doesn't point to the VENV python

**Review by davidabrahams — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/18)* status: altodyte must resolve 1 discussion (waiting on @altodyte and @shanekelly)

___
*[python/main.py, line 1 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/18#-Lo8z78dAFYv06IIE5sU:-Lo90Y3-AQPWWSyztHlR:bqq9cif) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f9700bdd6c45857e555f6571e28a41de24728f6/python/main.py#L1)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

It feels like it is wrong that this doesn't point to the VENV python
</blockquote></details>

it actually will use ENV's python, if it is currently activated. You can look at `build`, it has the same shebang, and uses `ENV`'s python

**Review by davidabrahams — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/18)* status: altodyte must resolve 1 discussion (waiting on @altodyte and @shanekelly)

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/18#-Lo90jwBBW3WNKrZDbUp:-Lo90jwBBW3WNKrZDbUq:b1znet9) (no related file):*
:dango: from me!

---

**Review by PrimePalaver — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/18)* status: altodyte must resolve 1 discussion (waiting on @altodyte and @shanekelly)

**Review by PrimePalaver — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/18)* status: altodyte must resolve 1 discussion (waiting on @altodyte)

**Comment by billmwong** [comment]
___
*[python/main.py, line 1 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/18#-Lo8z78dAFYv06IIE5sU:-LoOWpdj79faxDRBoTKZ:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f9700bdd6c45857e555f6571e28a41de24728f6/python/main.py#L1)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

it actually will use ENV's python, if it is currently activated. You can look at `build`, it has the same shebang, and uses `ENV`'s python
</blockquote></details>

Done.

**Review by davidabrahams — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/18)* status: altodyte must resolve 1 discussion (waiting on @altodyte)

**Review by davidabrahams — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/18)* status: davidabrahams must resolve 1 discussion, altodyte must resolve 1 discussion (waiting on @altodyte)

___
*[python/main.py, line 1 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/18#-Lo8z78dAFYv06IIE5sU:-LoRHrImBmtO9VWM_qka:b-6vji8n) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f9700bdd6c45857e555f6571e28a41de24728f6/python/main.py#L1)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Given the makefile PR, I don't think making this executable provides too much benefit anymore. WDYT about closing this PR and rebasing the makefile PR on master?

**Comment by billmwong** [comment]
___
*[python/main.py, line 1 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/18#-Lo8z78dAFYv06IIE5sU:-Lo9By7t6QnuXskiXqaT:b-ad90rb) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f9700bdd6c45857e555f6571e28a41de24728f6/python/main.py#L1)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Given the makefile PR, I don't think making this executable provides too much benefit anymore. WDYT about closing this PR and rebasing the makefile PR on master?
</blockquote></details>

Yeah makes sense, will close

**Pull request closed without merging**
