### PR TITLE
Refactor WordState -> State, and split Drawable and Shape abstractions

### PR DESCRIPTION
**Pull request by davidabrahams**
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/7)

### CODE REVIEW

**Review by PrimePalaver — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/7)* status: :shipit: complete! all files reviewed, 2 unresolved discussions (waiting on @altodyte and @davidabrahams)

___
*[python/state/ball.py, line 1 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/7#-LncupvCDDzeVuuc_YBe:-LncupvCDDzeVuuc_YBf:b-4iwius) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/4f40e2c32e733d07fa18e3df11173ebe09a7e4de/python/state/ball.py#L1)):*
> ```Python
> from typing import Tuple
> ```

Looks like `Tuple` might not be needed anymore (depending on the answer to my question below).
___
*[python/state/ball.py, line 35 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/7#-LncvHpB3q_NSgzYwhMY:-LncvHpB3q_NSgzYwhMZ:birthj0) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/4f40e2c32e733d07fa18e3df11173ebe09a7e4de/python/state/ball.py#L35)):*
> ```Python
> 
>         self.vx = 0
>         self.vy = 0
> ```

It's not clear to me why some variables have types and some don't. Should all of these have types?

**Review by davidabrahams — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/7)* status: billmwong must review 8 files, shanekelly must review 8 files, altodyte must review 8 files, shanekelly must resolve 2 discussions (waiting on @altodyte and @shanekelly)

___
*[python/state/ball.py, line 1 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/7#-LncupvCDDzeVuuc_YBe:-Lnd2DU87I-qYb7DF3tA:b-scvm15) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/4f40e2c32e733d07fa18e3df11173ebe09a7e4de/python/state/ball.py#L1)):*
<details><summary><i>Previously, shanekelly (Shane Kelly) wrote…</i></summary><blockquote>

Looks like `Tuple` might not be needed anymore (depending on the answer to my question below).
</blockquote></details>

gah, i didn't realize unused imports don't fail our code formatter.

Turns out flake8 will fail with unused imports. I switched to that: http://flake8.pycqa.org/en/latest/ (it looks like it runs 3 separate python checkers, including the formatter we had before). I also removed like 7 unused imports :)p
___
*[python/state/ball.py, line 35 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/7#-LncvHpB3q_NSgzYwhMY:-Lnd1sWX4exRu-DdmPxV:bg1h3ru) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/4f40e2c32e733d07fa18e3df11173ebe09a7e4de/python/state/ball.py#L35)):*
<details><summary><i>Previously, shanekelly (Shane Kelly) wrote…</i></summary><blockquote>

It's not clear to me why some variables have types and some don't. Should all of these have types?
</blockquote></details>

the types are actually inferred, so the type-checker knows these are `int`s. If later we try to do this:

```
def foo(s: str): ...

foo(ball.vx)
```

the type checker will fail.

Do you think a type annotation like:
```
self.vx: int = 0
```

is helpful, or just adds noise?

**Review by PrimePalaver — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/7)* status: shanekelly must resolve 2 discussions (waiting on @altodyte and @davidabrahams)

___
*[python/requirements.txt, line 9 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/7#-Lnd4ZFYCA-pb5HfopT3:-Lnd4ZFZAmz7tjLnGGPT:b-xx0vi) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/69bde935f56a4b110f49e92d2aa2d9d4920ae5a0/python/requirements.txt#L9)):*
> ```
> mypy==0.720
> mypy-extensions==0.4.1
> pycodestyle==2.5.0
> ```

Should `pycodestyle` be removed? Also, what are all these other things besides `flake8`?
___
*[python/state/ball.py, line 35 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/7#-LncvHpB3q_NSgzYwhMY:-Lnd5ILHDhqTJfB8zPjo:bpejt8j) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/4f40e2c32e733d07fa18e3df11173ebe09a7e4de/python/state/ball.py#L35)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

the types are actually inferred, so the type-checker knows these are `int`s. If later we try to do this:

```
def foo(s: str): ...

foo(ball.vx)
```

the type checker will fail.

Do you think a type annotation like:
```
self.vx: int = 0
```

is helpful, or just adds noise?
</blockquote></details>

I would be up for adding explicit types to everything initially and fine with changing later if we find that it is annoying. Also, should velocities be `float`s rather than `int`s?

**Review by davidabrahams — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/7)* status: shanekelly must resolve 2 discussions (waiting on @altodyte, @davidabrahams, and @shanekelly)

___
*[python/requirements.txt, line 9 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/7#-Lnd4ZFYCA-pb5HfopT3:-Lnd74Ei8daP1zOOpbgu:b2s40g6) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/69bde935f56a4b110f49e92d2aa2d9d4920ae5a0/python/requirements.txt#L9)):*
<details><summary><i>Previously, shanekelly (Shane Kelly) wrote…</i></summary><blockquote>

Should `pycodestyle` be removed? Also, what are all these other things besides `flake8`?
</blockquote></details>

ah woops, `hypothesis` is for my other testing pr.

flake8 runs pycodestyle, so its still needed. I wish there was an easier way to make sure you don't have dependencies you don't need, but I'm not sure how to do this with python :/

I updated this file to remove the deps we dont need for this pr

**Review by davidabrahams — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/7)* status: billmwong must review 1 file, shanekelly must review 1 file, altodyte must review 1 file, shanekelly must resolve 2 discussions (waiting on @altodyte and @shanekelly)

___
*[python/state/ball.py, line 35 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/7#-LncvHpB3q_NSgzYwhMY:-Lnd7MTI-Epb1dhQMgA0:b-xqdb64) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/4f40e2c32e733d07fa18e3df11173ebe09a7e4de/python/state/ball.py#L35)):*
<details><summary><i>Previously, shanekelly (Shane Kelly) wrote…</i></summary><blockquote>

I would be up for adding explicit types to everything initially and fine with changing later if we find that it is annoying. Also, should velocities be `float`s rather than `int`s?
</blockquote></details>

I think we should use ints as much as possible, and only floats when we absolutely need to (since theyre harder to test, and you have to do fuzzy-equality stuff). I now realize we don't have a unit on the velocity, so I added that.

**Review by PrimePalaver — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @altodyte)

**Pull request merged**
