### PR TITLE
Update apis to be immutable

### PR DESCRIPTION
**Pull request by davidabrahams**
I updated State/Ball/Flag to be immutable. For training, we will need to be able to keep track of state history, which means if we mutate State, we need to deepcopy() in order to have a record of what our state was. I did performance analysis on deepcopy(), and it is _awful_.

We pay a slight penalty in efficiency for this PR. I timed 1000 iterations of `next_state` and `handle_input`, these are the results:

Current master:
```
next_state took 0.029 seconds to execute
handle_input took 0.002 seconds to execute
```

This PR:
```
next_state took 0.049 seconds to execute
handle_input took 0.017 seconds to execute
```

I think being 2x less efficient, and avoiding a huge deepcopy() penalty later, is worth it. Additionally, this code is easier to reason about.

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21)

### CODE REVIEW

**Review by billmwong — APPROVED** [review]
> Reviewed 7 of 8 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21)* status: billmwong must resolve 4 discussions (waiting on @altodyte, @davidabrahams, and @shanekelly)

___
*[python/main.py, line 54 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21#-LoJIiSM0xXc37tkjkch:-LoJIiSN1fjQKn-gRxQc:bu049fx) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/af6364ee29ea0f8f1f2814bee90b5e47f6c62ae9/python/main.py#L54)):*
> ```Python
> 
>         world_state = world_state.handle_input(current_input)
>         world_state = world_state.next_state(delta_t_ms)
> ```

Should we rename to get_next_state and whatever the equivalent for handle_input would be
___
*[python/state/ball.py, line 73 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21#-LoJJg8ADVsMAiby5fj6:-LoJJg8ADVsMAiby5fj7:b74l4tr) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/bfe9db876e2c0b8d91de092e1fced7f9d8fc1afd/python/state/ball.py#L73)):*
> ```Python
>         self.ax, self.ay = self.accels_from_input(keypresses)
> 
>     def simulate_input(self, keypresses: Keys) -> 'Ball':
> ```

What did this simulate input func do before, why are we combining with handle_input
___
*[python/state/flag.py, line 10 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21#-LoJJreQ2-BXIJZyuvqM:-LoJJreQ2-BXIJZyuvqN:bv9bd3p) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/af6364ee29ea0f8f1f2814bee90b5e47f6c62ae9/python/state/flag.py#L10)):*
> ```Python
> 
> 
> @dataclass(frozen=True)
> ```

what does frozen mean
___
*[python/state/state.py, line 36 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21#-LoJKCy26wEHXOJFJdct:-LoJKCy26wEHXOJFJdcu:b-uymro3) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/af6364ee29ea0f8f1f2814bee90b5e47f6c62ae9/python/state/state.py#L36)):*
> ```Python
> 
>     def handle_input(self, user_input: Input) -> 'State':
>         def handle_ball_input(ball: Ball, commands: Dict[UUID, Keys]):
> ```

is a nested function considered good in python

**Review by davidabrahams — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21)* status: billmwong must resolve 4 discussions (waiting on @altodyte, @billmwong, and @shanekelly)

___
*[python/main.py, line 54 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21#-LoJIiSM0xXc37tkjkch:-LoJQfIZDp5EJ6xwTP8r:b-4p27vv) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/af6364ee29ea0f8f1f2814bee90b5e47f6c62ae9/python/main.py#L54)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Should we rename to get_next_state and whatever the equivalent for handle_input would be
</blockquote></details>

Hmm, I would expect a function called "nextState" to return the next state. I'm not sure that adding "get" adds any clarity? Also the return type is "State"
___
*[python/state/ball.py, line 73 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21#-LoJJg8ADVsMAiby5fj6:-LoJQKqUDMhOfUfG1n67:b6zcn0h) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/bfe9db876e2c0b8d91de092e1fced7f9d8fc1afd/python/state/ball.py#L73)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

What did this simulate input func do before, why are we combining with handle_input
</blockquote></details>

simulate input was the pure version of handle_input. Since now handle_input is pure, it's unneeded
___
*[python/state/flag.py, line 10 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21#-LoJJreQ2-BXIJZyuvqM:-LoJQV14-EKUJVYkFhg9:bxik0zv) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/af6364ee29ea0f8f1f2814bee90b5e47f6c62ae9/python/state/flag.py#L10)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

what does frozen mean
</blockquote></details>

https://docs.python.org/3/library/dataclasses.html
___
*[python/state/state.py, line 36 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21#-LoJKCy26wEHXOJFJdct:-LoJQWSD0kTE0UYz-gcX:b-rnlt7t) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/af6364ee29ea0f8f1f2814bee90b5e47f6c62ae9/python/state/state.py#L36)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

is a nested function considered good in python
</blockquote></details>

honestly not sure. Felt like the cleanest way to do this (the alternative was a long lambda, which seemed less readable)

**Review by billmwong — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21)* status: billmwong must resolve 2 discussions (waiting on @altodyte, @davidabrahams, and @shanekelly)

___
*[python/main.py, line 54 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21#-LoJIiSM0xXc37tkjkch:-LoJThF41XinnPEHa11p:bvpynhn) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/af6364ee29ea0f8f1f2814bee90b5e47f6c62ae9/python/main.py#L54)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Hmm, I would expect a function called "nextState" to return the next state. I'm not sure that adding "get" adds any clarity? Also the return type is "State"
</blockquote></details>

Sure, guess that makes sense.  It's not super clear from reading this why we need separate functions for handle input and next state, could they be the same function?  Seems weird to get a new state and then immediately get an even newer state.  That could just be my lack of understanding of this code though
___
*[python/state/state.py, line 36 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21#-LoJKCy26wEHXOJFJdct:-LoJVXtn9bEqYCb5Mn1q:b-k596dz) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/af6364ee29ea0f8f1f2814bee90b5e47f6c62ae9/python/state/state.py#L36)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

honestly not sure. Felt like the cleanest way to do this (the alternative was a long lambda, which seemed less readable)
</blockquote></details>

Cool okay.  What do we think about naming here?  "handle" seems not very descriptive.  Possibly related to my other comment

**Review by davidabrahams — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21)* status: billmwong must review 2 files, shanekelly must review 2 files, altodyte must review 2 files, billmwong must resolve 2 discussions (waiting on @altodyte, @billmwong, @davidabrahams, and @shanekelly)

___
*[python/main.py, line 54 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21#-LoJIiSM0xXc37tkjkch:-LoJWwrj6LoaFHb-ki8r:b-h5vuwe) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/af6364ee29ea0f8f1f2814bee90b5e47f6c62ae9/python/main.py#L54)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Sure, guess that makes sense.  It's not super clear from reading this why we need separate functions for handle input and next state, could they be the same function?  Seems weird to get a new state and then immediately get an even newer state.  That could just be my lack of understanding of this code though
</blockquote></details>

The high level difference is that next_state transitions state after a certain delta-time. handle_input embeds what inputs each ball is pressing in the state, so that once we call next_state(), State knows what accelerations to apply. Ie, I wouldn't call the state returned by "handle_inputs" a "new state", since it has an identical timestamp to the original state.

I like this suggestion. I don't think there's a good reason why the caller needs to remember to call both handle_input and next_state. Seems easy to forget to do one. I moved that logic into state.py, so the caller only needs to call next_state.

Let me know what you think about this

**Review by davidabrahams — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21)* status: billmwong must review 2 files, shanekelly must review 2 files, altodyte must review 2 files, billmwong must resolve 2 discussions (waiting on @altodyte, @billmwong, and @shanekelly)

___
*[python/state/state.py, line 36 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21#-LoJKCy26wEHXOJFJdct:-LoJ_7sL1yyQhaYvmzxf:b-ab47pr) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/af6364ee29ea0f8f1f2814bee90b5e47f6c62ae9/python/state/state.py#L36)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Cool okay.  What do we think about naming here?  "handle" seems not very descriptive.  Possibly related to my other comment
</blockquote></details>

Agreed. I renamed, not sure if this is better haha I did my best. Open the suggestions

**Review by billmwong — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21)* status: billmwong must resolve 1 discussion (waiting on @altodyte, @davidabrahams, and @shanekelly)

___
*[python/main.py, line 54 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21#-LoJIiSM0xXc37tkjkch:-LoJeam78a1bgGSj0zSk:b-jf5dk6) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/af6364ee29ea0f8f1f2814bee90b5e47f6c62ae9/python/main.py#L54)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

The high level difference is that next_state transitions state after a certain delta-time. handle_input embeds what inputs each ball is pressing in the state, so that once we call next_state(), State knows what accelerations to apply. Ie, I wouldn't call the state returned by "handle_inputs" a "new state", since it has an identical timestamp to the original state.

I like this suggestion. I don't think there's a good reason why the caller needs to remember to call both handle_input and next_state. Seems easy to forget to do one. I moved that logic into state.py, so the caller only needs to call next_state.

Let me know what you think about this
</blockquote></details>

OK LOVE IT
___
*[python/state/state.py, line 36 at r2](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21#-LoJKCy26wEHXOJFJdct:-LoJf8EP0rX-o3KSiVin:b-hvdcq6) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/af6364ee29ea0f8f1f2814bee90b5e47f6c62ae9/python/state/state.py#L36)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Agreed. I renamed, not sure if this is better haha I did my best. Open the suggestions
</blockquote></details>

OK yeah this makes sense to me now
___
*[python/state/state.py, line 86 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21#-LoJf5olB5RQyGDyYaTW:-LoJf5olB5RQyGDyYaTX:bkpvl96) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/10f59235c564ca81751febb6bb8b7a877a7e026e/python/state/state.py#L86)):*
> ```Python
>     def next_state(self, user_input: Input, dt: int) -> 'State':
>         """
>         :param int dt: time elapsed in milliseconds
> ```

param for user_input?

**Review by davidabrahams — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21)* status: billmwong must review 1 file, shanekelly must review 1 file, altodyte must review 1 file, billmwong must resolve 1 discussion (waiting on @altodyte, @billmwong, and @shanekelly)

___
*[python/state/state.py, line 86 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21#-LoJf5olB5RQyGDyYaTW:-LoJiQrjAPrcondA1ug9:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/10f59235c564ca81751febb6bb8b7a877a7e026e/python/state/state.py#L86)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

param for user_input?
</blockquote></details>

Done.

**Review by billmwong — APPROVED** [review]
:dango: :dango: 

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/21#-:-LoJk_5V-7gHmiAwrl4C:bdd6633)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @altodyte and @shanekelly)

**Pull request merged**
