### PR TITLE
Initial visualizations

### PR DESCRIPTION
**Pull request by altodyte**
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/5)

### CODE REVIEW

**Review by davidabrahams — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/5)* status: davidabrahams must review 5 files, billmwong must review 5 files, shanek21 must review 5 files, davidabrahams must resolve 2 discussions (waiting on @altodyte and @davidabrahams)

___
*[python/main.py, line 26 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/5#-LnaMlGa4_mPWmw97g6g:-LnaMlGa4_mPWmw97g6h:b-l6mwxj) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/4d1334586069f888917ac0ed58be5538b7b56079/python/main.py#L26)):*
> ```Python
>             if event.type == pygame.QUIT:
>                 done = True
>             # if event.type == pygame.KEYDOWN and event.key == pygame.K_SPACE:
> ```

remove
___
*[python/world_state/worldstate.py, line 26 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/5#-LnaU8W6EcCnYI5_bpic:-LnaU8W6EcCnYI5_bpid:bbvh9bl) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/ff7e0815ba161181c14614434d3fbd63d5b7904f/python/world_state/worldstate.py#L26)):*
> ```Python
>         for blue_ball in self.blue_balls:
>             if blue_ball.id in self.balls:
>                 raise ValueError(
> ```

I think this can be done more concisely by checking at the top that all balls `id`s are unique. We should also check that there are no red balls with the same id as any blue balls. Something like
```
ids = map((red_balls + blue_balls + [ego_ball]), lambda b: b.id)
assert(len(set(ids)) == len(ids))
```

**Review by davidabrahams — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 1 files at r5, 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/5)* status: davidabrahams must review 3 files, billmwong must review 3 files, shanek21 must review 3 files, davidabrahams must resolve 1 discussion (waiting on @altodyte and @davidabrahams)

___
*[python/world_state/worldstate.py, line 17 at r6](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/5#-LnaZrZB9uJcSc7fM-f4:-LnaZrZB9uJcSc7fM-f5:b-65c2v1) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/eb6b6aa38b71aaecdb8efeb58c6257d1925f721b/python/world_state/worldstate.py#L17)):*
> ```Python
>         assert(len(friendly_balls) < 4)
> 
>         self.screen = screen
> ```

IMO State shouldn't have a reference to Screen, since it doesn't really have to do with the state of the tagpro world.

**Review by davidabrahams — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/5)* status: davidabrahams must review 3 files, billmwong must review 3 files, shanek21 must review 3 files, davidabrahams must resolve 3 discussions (waiting on @altodyte and @davidabrahams)

___
*[python/world_state/worldstate.py, line 24 at r6](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/5#-LnaZzbwBg1QLrpJDWGo:-LnaZzbwBg1QLrpJDWGp:b-8iwtb7) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/eb6b6aa38b71aaecdb8efeb58c6257d1925f721b/python/world_state/worldstate.py#L24)):*
> ```Python
> 
>         all_balls = enemy_balls + friendly_balls + [ego_ball]
>         print(all_balls)
> ```

remove prints
___
*[python/world_state/worldstate.py, line 27 at r6](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/5#-Lna_0U-Dj-fJ2XeMp4O:-Lna_0U-Dj-fJ2XeMp4P:b-s6kg26) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/eb6b6aa38b71aaecdb8efeb58c6257d1925f721b/python/world_state/worldstate.py#L27)):*
> ```Python
>         ids: List[uuid.UUID] = list(map(lambda b: b.id, all_balls))
>         print(ids)
>         assert(len(set(ids)) == len(ids))
> ```

can we do these asserts at the top of the function before we do some assigns?

**Review by davidabrahams — APPROVED** [review]
> Reviewed 1 of 11 files at r1, 1 of 3 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @altodyte)

**Review by altodyte — COMMENTED** [review]
> Reviewed 6 of 11 files at r1, 2 of 4 files at r2, 1 of 1 files at r5, 1 of 3 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
