### PR TITLE
Initial state transition code

### PR DESCRIPTION
**Pull request by davidabrahams**
I set up the API for state transitions:

`(State, deltaTime) => State`

and integrated it with the main loop.

I also put some stuff in the style guide.

---
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10)

### CODE REVIEW

**Review by altodyte — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10)* status: altodyte must resolve 4 discussions (waiting on @davidabrahams and @shanekelly)

___
*[python/main.py, line 30 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfWUUh4y_DfOmyqgr9:-LnfWUUh4y_DfOmyqgrA:bf2gh7s) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/main.py#L30)):*
> ```Python
> 
>         screen.fill((0, 0, 0))
>         clock.tick(10)
> ```

I am not sure we want to go this slow. According to https://www.reddit.com/r/TagPro/wiki/physics, tagpo physics updates at 60Hz, which we'll probably want to use as well.
___
*[python/performance/performance.py, line 8 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfWrNUAFv45-UorWkl:-LnfWrNUAFv45-UorWkm:b9qg4bm) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/performance/performance.py#L8)):*
> ```Python
> 
> """
> Some performance profiling of different styles of Python code. The goal is to
> ```

nit This filename is too generic. Suggest `point_update_performance.py` or similar
___
*[python/performance/performance.py, line 29 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfX8f_9TzJEQIqpz33:-LnfX8f_9TzJEQIqpz34:bcrd7yx) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/performance/performance.py#L29)):*
> ```Python
> 2. profile_point0: 0.18
> 3. profile_point1: 0.35
> 4. profile_point_class0: 1.08
> ```

do these names exactly match the names below? I'm a bit lost reading these results against those names
___
*[python/state/ball.py, line 17 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfVaxyEEoR0lX5f7wq:-LnfVaxyEEoR0lX5f7wr:bdz7l73) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/state/ball.py#L17)):*
> ```Python
> @dataclass
> class Ball(Shape):
>     x: int
> ```

btw As discussed IRL we probably want to store the position and velocity as floats, and have the `get_shape(...)` function round
___
*[python/state/ball.py, line 42 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfW79n4yyloVfDtgsU:-LnfW79n4yyloVfDtgsV:bp5vxr1) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/state/ball.py#L42)):*
> ```Python
>                             2*self.radius))
> 
>     def move(self, dt: int) -> None:
> ```

btw I think all of our move functions (maybe starting in the next PR) will need to include tagpro physics or at least require `Input` as an input
___
*[python/state/flag.py, line 9 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfVJ972H5HoMz6s-ou:-LnfVJ972H5HoMz6s-ov:b-3pb99i) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/state/flag.py#L9)):*
> ```Python
> 
> 
> @dataclass(frozen=True)
> ```

btw is this the better performance option? I thought we had discussed IRL that this was slower
___
*[python/state/state.py, line 12 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfUl8r2thcYcrKQj0w:-LnfUl8r2thcYcrKQj0x:b3pcjru) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/state/state.py#L12)):*
> ```Python
> 
> @dataclass
> class State(Drawable):
> ```

I think we should take in a single list of `Ball`s and in `__post_init__` create a dictionary from UUID to Ball.
___
*[python/state/state.py, line 34 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfVB63A0OhmFNtOlHD:-LnfVB63A0OhmFNtOlHE:bqbshlk) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/state/state.py#L34)):*
> ```Python
>         self.flag.draw(screen)
> 
>     def handle_inputs(self, input: Input) -> 'State':
> ```

btw We'll probably want to weigh performance on this function
___
*[python/state/state.py, line 38 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfUxkaDpmdOzRCD7Ti:-LnfUxkaDpmdOzRCD7Tj:bkm0478) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/state/state.py#L38)):*
> ```Python
>         return self
> 
>     def next_state(self, dt: int) -> None:
> ```

I think this is fine for now, but a `next_state(...)` without a list of `Input`s is probably nonsensical

**Review by altodyte — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10)* status: altodyte must resolve 5 discussions (waiting on @davidabrahams and @shanekelly)

___
*[python/state/flag.py, line 5 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfXtSC-D01Jl8d3Qa9:-LnfXtSDAii5KUxO7T4I:b6jb3ed) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/state/flag.py#L5)):*
> ```Python
> from visualization.shape import Shape
> 
> side_length = 20
> ```

My mistake for introducing this error, but while you're responding to other changes, would you mind setting this to the correct value, 30?
https://www.reddit.com/r/TagPro/wiki/physics#wiki_the_size_of_various_elements

**Review by davidabrahams — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10)* status: billmwong must review 4 files, shanekelly must review 4 files, altodyte must review 4 files, altodyte must resolve 5 discussions (waiting on @altodyte and @shanekelly)

___
*[python/main.py, line 30 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfWUUh4y_DfOmyqgr9:-LnfZAbbBm2DGYzsQziH:b-1te7pr) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/main.py#L30)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

I am not sure we want to go this slow. According to https://www.reddit.com/r/TagPro/wiki/physics, tagpo physics updates at 60Hz, which we'll probably want to use as well.
</blockquote></details>

Done. upped to 100
___
*[python/state/ball.py, line 17 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfVaxyEEoR0lX5f7wq:-LnfZjWD58XYDYXE7RvI:b-bojn9e) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/state/ball.py#L17)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

btw As discussed IRL we probably want to store the position and velocity as floats, and have the `get_shape(...)` function round
</blockquote></details>

I think velocity as int is fine. agreed about position, done
___
*[python/state/ball.py, line 42 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfW79n4yyloVfDtgsU:-LnfZo6QDkNIPYGhHhDm:b-pxefnd) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/state/ball.py#L42)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

btw I think all of our move functions (maybe starting in the next PR) will need to include tagpro physics or at least require `Input` as an input
</blockquote></details>

I'm not sure I agree? Maybe we can discuss IRL
___
*[python/state/flag.py, line 5 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfXtSC-D01Jl8d3Qa9:-LnfZvnM1l1ahDn5wfi4:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/state/flag.py#L5)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

My mistake for introducing this error, but while you're responding to other changes, would you mind setting this to the correct value, 30?
https://www.reddit.com/r/TagPro/wiki/physics#wiki_the_size_of_various_elements
</blockquote></details>

Done.
___
*[python/state/flag.py, line 9 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfVJ972H5HoMz6s-ou:-LnfZxfU0r8-GY6P1Yb4:b-vgm0gk) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/state/flag.py#L9)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

btw is this the better performance option? I thought we had discussed IRL that this was slower
</blockquote></details>

oh, yeah i can unfreeze this
___
*[python/state/state.py, line 12 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfUl8r2thcYcrKQj0w:-Lnf_3nv3A0iynXy-1rS:b-qnl1bc) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/state/state.py#L12)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

I think we should take in a single list of `Ball`s and in `__post_init__` create a dictionary from UUID to Ball.
</blockquote></details>

Can we do in follow up?
___
*[python/state/state.py, line 34 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfVB63A0OhmFNtOlHD:-Lnf_8jz-yL1QoFssH7K:bybls5r) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/state/state.py#L34)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

btw We'll probably want to weigh performance on this function
</blockquote></details>

ah yeah this should probably return None
___
*[python/state/state.py, line 38 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfUxkaDpmdOzRCD7Ti:-Lnf_AeN-YX2yZm2vclM:b-mxse3k) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/state/state.py#L38)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

I think this is fine for now, but a `next_state(...)` without a list of `Input`s is probably nonsensical
</blockquote></details>

lets discuss IRL
___
*[python/performance/performance.py, line 29 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-LnfX8f_9TzJEQIqpz33:-LnfZgHc4uGOJZXD0FBs:b2e4yli) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/67e25cb896b0874d91a4959f9f87a2806ba5339b/python/performance/performance.py#L29)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

do these names exactly match the names below? I'm a bit lost reading these results against those names
</blockquote></details>

Done. i renamed the functions and forgot to update this

**Review by altodyte — COMMENTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10)* status: billmwong must review 1 file, shanekelly must review 1 file, altodyte must review 1 file (waiting on @altodyte and @shanekelly)

**Review by altodyte — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10)* status: :shipit: complete! all files reviewed, 1 unresolved discussion (waiting on @davidabrahams and @shanekelly)

___
*[python/state/state.py, line 20 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/10#-Lnfd31-4HrZ0blAShRQ:-Lnfd31-4HrZ0blAShRR:b-ji2asn) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/3c5e4a78555117aa47ad07876e90e14221f5174e/python/state/state.py#L20)):*
> ```Python
>         assert(num_foe_balls <= 4)
>         assert(num_friendly_balls < 4)
>         assert(len(self.balls) == len(balls))
> ```

nit: we should also assert that there is exactly one ego ball here

**Pull request merged**
