### PR TITLE
Add makefile

### PR DESCRIPTION
**Pull request by billmwong**
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)

### CODE REVIEW

**Review by davidabrahams — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: davidabrahams must review 1 file, shanekelly must review 1 file, altodyte must review 1 file, davidabrahams must resolve 3 discussions, target branch is not master (waiting on @billmwong)

___
*[python/Makefile, line 3 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-Lo9FtBw92FKs7NMgsXZ:-Lo9FtBx0uObBdgtmpjS:b-gsn0he) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/edf505ba8f2d539b52c1b36cbed8b61a467ebad2/python/Makefile#L3)):*
> ```Makefile
> SHELL = /bin/bash
> .PHONY: env install freeze run build
> .SILENT: env install freeze run build
> ```

I think getting output from these commands is useful
___
*[python/Makefile, line 5 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-Lo9FxInEh12EFdcuEHI:-Lo9FxInEh12EFdcuEHJ:b-3qfo64) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/edf505ba8f2d539b52c1b36cbed8b61a467ebad2/python/Makefile#L5)):*
> ```Makefile
> .SILENT: env install freeze run build
> 
> activate = source ENV/bin/activate
> ```

why is this on one line and the others are multline?
___
*[python/Makefile, line 17 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-Lo9G65K4ViCboMWWG_5:-Lo9G65K4ViCboMWWG_6:b-p4yi4g) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/edf505ba8f2d539b52c1b36cbed8b61a467ebad2/python/Makefile#L17)):*
> ```Makefile
> 
> run:
> 	($(call activate);./main.py;)
> ```

I think we can just remove activate from this, and use `ENV/bin/python main.py` here (and below)

**Review by davidabrahams — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: davidabrahams must resolve 3 discussions, target branch is not master (waiting on @billmwong)

**Review by billmwong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: davidabrahams must resolve 3 discussions, billmwong must resolve 1 discussion, target branch is not master (waiting on @billmwong and @davidabrahams)

___
*[python/Makefile, line 5 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-Lo9FxInEh12EFdcuEHI:-Lo9IVRsCoYzBMqavDwm:b-h0yvo4) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/edf505ba8f2d539b52c1b36cbed8b61a467ebad2/python/Makefile#L5)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

why is this on one line and the others are multline?
</blockquote></details>

This is a function not a public command.  Wouldn't be useful as a public command cause it only affects the make process
___
*[python/Makefile, line 17 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-Lo9G65K4ViCboMWWG_5:-Lo9IhDz3jnbtrxS4UK1:b-924a2r) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/edf505ba8f2d539b52c1b36cbed8b61a467ebad2/python/Makefile#L17)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I think we can just remove activate from this, and use `ENV/bin/python main.py` here (and below)
</blockquote></details>

Will do for this, but would that work for build?

**Comment by billmwong** [comment]
___
*[python/Makefile, line 3 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-Lo9FtBw92FKs7NMgsXZ:-Lo9JM4w9KuGdukGzf93:buus3xv) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/edf505ba8f2d539b52c1b36cbed8b61a467ebad2/python/Makefile#L3)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I think getting output from these commands is useful
</blockquote></details>

SILENT just prevents the echo of the command not the actual output of the command.  That being said, I added this when the commands looked more messy so maybe I can add it back

**Comment by billmwong** [comment]
___
*[python/Makefile, line 5 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-Lo9FxInEh12EFdcuEHI:-Lo9JlAa22K_vBCZ5-AO:b17295c) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/edf505ba8f2d539b52c1b36cbed8b61a467ebad2/python/Makefile#L5)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

This is a function not a public command.  Wouldn't be useful as a public command cause it only affects the make process
</blockquote></details>

Not sure how to do a multiline function actually, I can try to do that if the syntax consistency is important

**Review by davidabrahams — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: davidabrahams must resolve 2 discussions, billmwong must resolve 1 discussion, target branch is not master (waiting on @billmwong and @davidabrahams)

___
*[python/Makefile, line 3 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-Lo9FtBw92FKs7NMgsXZ:-Lo9KxLQ-3atIeJRgI7M:b-ljnzvc) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/edf505ba8f2d539b52c1b36cbed8b61a467ebad2/python/Makefile#L3)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

SILENT just prevents the echo of the command not the actual output of the command.  That being said, I added this when the commands looked more messy so maybe I can add it back
</blockquote></details>

ah didn't know that. im cool with it either way
___
*[python/Makefile, line 17 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-Lo9G65K4ViCboMWWG_5:-Lo9L7Ic6h-RF4npAK_s:bw421vc) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/edf505ba8f2d539b52c1b36cbed8b61a467ebad2/python/Makefile#L17)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Will do for this, but would that work for build?
</blockquote></details>

yup! just tried it. can do `ENV/bin/python build`

**Comment by billmwong** [comment]
___
*[python/Makefile, line 17 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-Lo9G65K4ViCboMWWG_5:-Lo9QUYvBDCJaeml1Jg0:b-ddrj1y) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/edf505ba8f2d539b52c1b36cbed8b61a467ebad2/python/Makefile#L17)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

yup! just tried it. can do `ENV/bin/python build`
</blockquote></details>

Hmm I cannot :( It gives me "sh: flake8: command not found"

**Review by davidabrahams — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: davidabrahams must resolve 1 discussion, billmwong must resolve 1 discussion, target branch is not master (waiting on @billmwong)

___
*[python/Makefile, line 17 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-Lo9G65K4ViCboMWWG_5:-Lo9U6Ir9kmH2suaImDc:btfct56) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/edf505ba8f2d539b52c1b36cbed8b61a467ebad2/python/Makefile#L17)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Hmm I cannot :( It gives me "sh: flake8: command not found"
</blockquote></details>

hrmmm. thats weird... does `ENV/bin/python` work on its own for you? (not using the makefile)

**Comment by billmwong** [comment]
___
*[python/Makefile, line 17 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-Lo9G65K4ViCboMWWG_5:-Lo9UVBm3muXapmT80aR:b-pwcgca) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/edf505ba8f2d539b52c1b36cbed8b61a467ebad2/python/Makefile#L17)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

hrmmm. thats weird... does `ENV/bin/python` work on its own for you? (not using the makefile)
</blockquote></details>

Yeah it work with main.py

**Review by davidabrahams — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: billmwong must resolve 1 discussion, target branch is not master (waiting on @billmwong)

___
*[python/Makefile, line 17 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-Lo9G65K4ViCboMWWG_5:-Lo9XGap8_KgE-FVc8Ya:bv0jnkj) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/edf505ba8f2d539b52c1b36cbed8b61a467ebad2/python/Makefile#L17)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Yeah it work with main.py
</blockquote></details>

ohhh its because of the shebang on top, which forces it to use your current environment. In that case, I'm fine with leaving the `activate` thing in here

**Review by davidabrahams — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: billmwong must resolve 1 discussion, target branch is not master (waiting on @billmwong)

**Comment by billmwong** [comment]
___
*[python/Makefile, line 3 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-Lo9FtBw92FKs7NMgsXZ:-Lo9YIfq6wp5LzSW3Li0:btsvl5w) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/edf505ba8f2d539b52c1b36cbed8b61a467ebad2/python/Makefile#L3)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

ah didn't know that. im cool with it either way
</blockquote></details>

Decided to remove the silent

**Review by davidabrahams — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: billmwong must resolve 1 discussion, target branch is not master (waiting on @billmwong)

**Review by PrimePalaver — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: target branch is not master

**Review by PrimePalaver — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: target branch is not master

**Review by davidabrahams — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: davidabrahams must resolve 2 discussions, target branch is not master (waiting on @billmwong)

___
*[python/build, line 44 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoRH1eX9FL8n0s7GNwt:-LoRH1eX9FL8n0s7GNwu:b-y24tc9) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/build#L44)):*
> ```
> all_checks = [flake8_passed, mypy_passed, unittest_passed]
> if all(all_checks):
>     print("🍡 All checks passed 🍡")
> ```

this line really is the most significant and impactful change made to this project in years
___
*[python/Makefile, line 18 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoRHN5E6K-dHjrNYLn6:-LoRHN5E6K-dHjrNYLn7:b-ugr9p9) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/Makefile#L18)):*
> ```Makefile
> 	($(call activate);./main.py;)
> 
> mypy:
> ```

I remember seeing you run this and it seems like `make` puts a bunch of noisy output along with mypy/flake/etc's output. Should we `SILENT` these?
___
*[python/README.md, line 14 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoRH_1B9ERE7USRxcpc:-LoRH_1B9ERE7USRxcpd:b-rv81ct) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/README.md#L14)):*
> ```Markdown
> Make a virtual environment and install dependencies:
> 
> ```sh
> ```

IMO we should leave instructions for users who want to manually handle their python environment

**Review by billmwong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: davidabrahams must resolve 2 discussions (waiting on @davidabrahams)

___
*[python/Makefile, line 18 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoRHN5E6K-dHjrNYLn6:-LoUEFgu2xLroybRYvi4:b-2k09a5) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/Makefile#L18)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I remember seeing you run this and it seems like `make` puts a bunch of noisy output along with mypy/flake/etc's output. Should we `SILENT` these?
</blockquote></details>

I wouldn't call it a bunch, it just prints out the line that it runs, so this would print "($(call activate);mypy .;)"
I find it useful to know what it's doing under the hood but it is extra output. Open to making them silent if the team wants to
___
*[python/README.md, line 14 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoRH_1B9ERE7USRxcpc:-LoUEwb3Azr7MuFy3aiZ:b221zed) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/README.md#L14)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

IMO we should leave instructions for users who want to manually handle their python environment
</blockquote></details>

Hmm maybe fair
Would keeping the non-silent make commands cover this concern?

**Review by davidabrahams — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: davidabrahams must resolve 2 discussions (waiting on @billmwong and @davidabrahams)

___
*[python/README.md, line 14 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoRH_1B9ERE7USRxcpc:-LoYTc9i1sHz2O99tlWz:bneh6dz) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/README.md#L14)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Hmm maybe fair
Would keeping the non-silent make commands cover this concern?
</blockquote></details>

I think s/t like

You can also manage your own python environment. Here is how you can create and activate a python3 virtual environment with the required dependencies:

(put old commands here)

**Review by davidabrahams — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: davidabrahams must resolve 1 discussion (waiting on @billmwong)

___
*[python/Makefile, line 18 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoRHN5E6K-dHjrNYLn6:-LoYUU2t4sB58v5ZddW1:b-92tcja) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/Makefile#L18)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

I wouldn't call it a bunch, it just prints out the line that it runs, so this would print "($(call activate);mypy .;)"
I find it useful to know what it's doing under the hood but it is extra output. Open to making them silent if the team wants to
</blockquote></details>

Ah got it. I just tried running it, I agree having it print what it's doing it kind of nice. :dango:

**Review by davidabrahams — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: davidabrahams must resolve 2 discussions (waiting on @billmwong)

___
*[python/Makefile, line 16 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoYUiy1EHIgsKMRpohj:-LoYUiy1EHIgsKMRpohk:b-h8ysnw) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/Makefile#L16)):*
> ```Makefile
> 
> run:
> 	($(call activate);./main.py;)
> ```

Given all this fanciness, can you update `.travis.yml` to use these commands? Something like:

```
dist: bionic # use Ubuntu 18.04 as our build environment
language: python
python:
  - "3.7"
before_install:
  - cd python
install:
  - make env
  - make install
script:
  - ./build
```
___
*[python/Makefile, line 28 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoYVP6T2t71UKQVdJUv:-LoYVP6T2t71UKQVdJUw:b-1yly4p) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/Makefile#L28)):*
> ```Makefile
> 
> build:
> 	($(call activate);./build;)
> ```

FYI one nit: the output of `make build` is kinda gross:

```shell
(ENV) ➜  python git:(makefile) ✗ make build
(source ENV/bin/activate;./build;)
make[1]: Entering directory '/home/david/tagprobot-ml/python'
(source ENV/bin/activate;flake8;)
make[1]: Leaving directory '/home/david/tagprobot-ml/python'
make[1]: Entering directory '/home/david/tagprobot-ml/python'
(source ENV/bin/activate;mypy .;)
make[1]: Leaving directory '/home/david/tagprobot-ml/python'
make[1]: Entering directory '/home/david/tagprobot-ml/python'
(source ENV/bin/activate;python -m unittest;)
.
----------------------------------------------------------------------
Ran 1 test in 0.068s

OK
make[1]: Leaving directory '/home/david/tagprobot-ml/python'
🍡 All checks passed 🍡
```

And i'll probably end up running `./build` anyway, since it's so short to type. Not sure if we can clean up this output? Even if not, it's fine leaving `make build` here if it's useful for you, just thought I'd note this.

**Comment by billmwong** [comment]
___
*[python/Makefile, line 28 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoYVP6T2t71UKQVdJUv:-LoYmkfwE7_a22ABk7uK:b15u3yp) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/Makefile#L28)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

FYI one nit: the output of `make build` is kinda gross:

```shell
(ENV) ➜  python git:(makefile) ✗ make build
(source ENV/bin/activate;./build;)
make[1]: Entering directory '/home/david/tagprobot-ml/python'
(source ENV/bin/activate;flake8;)
make[1]: Leaving directory '/home/david/tagprobot-ml/python'
make[1]: Entering directory '/home/david/tagprobot-ml/python'
(source ENV/bin/activate;mypy .;)
make[1]: Leaving directory '/home/david/tagprobot-ml/python'
make[1]: Entering directory '/home/david/tagprobot-ml/python'
(source ENV/bin/activate;python -m unittest;)
.
----------------------------------------------------------------------
Ran 1 test in 0.068s

OK
make[1]: Leaving directory '/home/david/tagprobot-ml/python'
🍡 All checks passed 🍡
```

And i'll probably end up running `./build` anyway, since it's so short to type. Not sure if we can clean up this output? Even if not, it's fine leaving `make build` here if it's useful for you, just thought I'd note this.
</blockquote></details>

Hmm weird, make does not print the entering/leaving directory lines for me.  Yeah if that happens on ubuntu then that's bad.  Would be down to try to research a fix but I won't be able to test it on mac

**Comment by billmwong** [comment]
___
*[python/Makefile, line 16 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoYUiy1EHIgsKMRpohj:-Lp1u9pa8AOWG-H4LMTx:b-8j54qm) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/Makefile#L16)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Given all this fanciness, can you update `.travis.yml` to use these commands? Something like:

```
dist: bionic # use Ubuntu 18.04 as our build environment
language: python
python:
  - "3.7"
before_install:
  - cd python
install:
  - make env
  - make install
script:
  - ./build
```
</blockquote></details>

literally where is this file i can't find it

**Comment by billmwong** [comment]
___
*[python/Makefile, line 16 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoYUiy1EHIgsKMRpohj:-Lp1uQum42BwiUTUYQhV:b36zvi5) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/Makefile#L16)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

literally where is this file i can't find it
</blockquote></details>

ah found it

**Comment by billmwong** [comment]
___
*[python/README.md, line 14 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoRH_1B9ERE7USRxcpc:-Lp1v9vF0cYiPcMPfzS5:bhf860p) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/README.md#L14)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I think s/t like

You can also manage your own python environment. Here is how you can create and activate a python3 virtual environment with the required dependencies:

(put old commands here)
</blockquote></details>

if you wanna manage your own environment will you not know how to do this naturally or figure it out from the makefile

**Comment by billmwong** [comment]
___
*[python/README.md, line 14 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoRH_1B9ERE7USRxcpc:-Lp1vHec09yf-LkVMKPq:b9scwnz) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/README.md#L14)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

if you wanna manage your own environment will you not know how to do this naturally or figure it out from the makefile
</blockquote></details>

Just wanna avoid changing this in multiple places if we change it

**Comment by billmwong** [comment]
___
*[python/Makefile, line 16 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoYUiy1EHIgsKMRpohj:-Lp1w3fH0coMHRwZRCFQ:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/Makefile#L16)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

ah found it
</blockquote></details>

Done.

**Comment by billmwong** [comment]
___
*[python/README.md, line 14 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoRH_1B9ERE7USRxcpc:-Lp1wN5IADbol_XD7Hrx:b-n8ys3m) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/README.md#L14)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

Just wanna avoid changing this in multiple places if we change it
</blockquote></details>

I'm also confused, do you just want a separate section that says this:

You can also manage your own python environment. Here is how you can create and activate a python3 virtual environment with the required dependencies:
```
python3.7 -m venv ENV
source ENV/bin/activate
pip install -r requirements.txt

python main.py

mypy . # type checker
flake8 # style checker
python -m unittest

./build
./build --fix

pip freeze > requirements.txt
```

**Review by davidabrahams — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: davidabrahams must review 2 files, shanekelly must review 2 files, altodyte must review 2 files, davidabrahams must resolve 1 discussion (waiting on @billmwong and @davidabrahams)

___
*[python/README.md, line 14 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoRH_1B9ERE7USRxcpc:-Lp4OZ6W-PJOst9HR9O9:bpg7p1g) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/README.md#L14)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

I'm also confused, do you just want a separate section that says this:

You can also manage your own python environment. Here is how you can create and activate a python3 virtual environment with the required dependencies:
```
python3.7 -m venv ENV
source ENV/bin/activate
pip install -r requirements.txt

python main.py

mypy . # type checker
flake8 # style checker
python -m unittest

./build
./build --fix

pip freeze > requirements.txt
```

</blockquote></details>

Haha yup that's what I want (with comments or something explaining what each thing does)

**Review by davidabrahams — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: davidabrahams must resolve 1 discussion (waiting on @billmwong)

**Comment by billmwong** [comment]
___
*[python/README.md, line 14 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoRH_1B9ERE7USRxcpc:-LpCNLneC8gWPm0Qyg4s:b-q22d9a) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/README.md#L14)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

Haha yup that's what I want (with comments or something explaining what each thing does)
</blockquote></details>

FINE MAYBE I WILL

**Review by billmwong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: davidabrahams must review 1 file, shanekelly must review 1 file, altodyte must review 1 file, davidabrahams must resolve 1 discussion (waiting on @davidabrahams)

___
*[python/README.md, line 14 at r3](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LoRH_1B9ERE7USRxcpc:-LpCOSDM9hPg-QlHvDqa:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/5f91aa33be2b0e2a8c362eae7c137f9a14bde36c/python/README.md#L14)):*
<details><summary><i>Previously, billmwong (Bill Wong) wrote…</i></summary><blockquote>

FINE MAYBE I WILL
</blockquote></details>

Done.

**Review by davidabrahams — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: davidabrahams must review 1 file, shanekelly must review 1 file, altodyte must review 1 file, davidabrahams must resolve 1 discussion (waiting on @billmwong and @davidabrahams)

___
*[python/README.md, line 77 at r5](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20#-LpElP-JAXD9LULtdXvH:-LpElP-JAXD9LULtdXvI:b-tdu13c) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/4933d4c7f6644814a898b2fc822398d9548cfb9e/python/README.md#L77)):*
> ```Markdown
> ./build --fix # run the build script with auto-format
> 
> pip freeze > requirements.txt # add packages
> ```

Can you separate this out into different sections? It sort of reads like all of these steps are required to set up a python environment

**Review by davidabrahams — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: davidabrahams must resolve 1 discussion (waiting on @billmwong)

**Review by davidabrahams — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/20)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
