### PR TITLE
Initial heuristics

### PR DESCRIPTION
**Pull request by altodyte**
This change is [Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15)

### CODE REVIEW

**Review by davidabrahams — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15)* status: davidabrahams must resolve 7 discussions (waiting on @altodyte)

___
*[python/main.py, line 41 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15#-LnikDztDpcul-XnFrv7:-LnikDztDpcul-XnFrv8:b-8zb0d5) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/6313f2646c102c83643e60325af0fc3de2d251ee/python/main.py#L41)):*
> ```Python
> 
>         pygame_pressed = pygame.key.get_pressed()
>         if pygame_pressed[pygame.K_SPACE]:
> ```

can you comment the high level intent of this block?

```
while space is pressed, we try to random walk to the flag. If randomly generated keypresses are worse than doing nothing, we do nothing.
```
___
*[python/main.py, line 47 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15#-LnikTDT656hfrL1etpx:-LnikTDT656hfrL1etpy:b-xa3x8x) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/6313f2646c102c83643e60325af0fc3de2d251ee/python/main.py#L47)):*
> ```Python
>             future_ball = ego_ball.simulate_input(possible_keys)
>             future_ball.update(delta_t_ms)  # todo this seems wrong
>             possible_world = copy.deepcopy(world_state)
> ```

we should make a function on `State` which is something like: `def updateBall(ball_id, ball) -> State` so we don't need to deepcopy here
___
*[python/input/input.py, line 22 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15#-LnikmdB8nsJIZ3vhwR6:-LnikmdB8nsJIZ3vhwR7:bvej8u1) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/6313f2646c102c83643e60325af0fc3de2d251ee/python/input/input.py#L22)):*
> ```Python
>     @staticmethod
>     def random_keys() -> 'Keys':
>         press_left = bool(random.getrandbits(1))
> ```

FYI This will cause us to always move along a 45 degree angle. I think its fine for now since most of this is placeholder code, just wanted to point out
___
*[python/state/ball.py, line 46 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15#-Lnikyyo-rziCMCKsrE9:-Lnikyyo-rziCMCKsrEA:b93dn7) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/6313f2646c102c83643e60325af0fc3de2d251ee/python/state/ball.py#L46)):*
> ```Python
>     on_team_tile: bool = False
> 
>     radius: int = radius
> ```

we should have radius stored in one place. My original rational for having it outside the class was that if every ball will always have the exact same radius, we don't need to store it separately for each instance. I think we should either stick to this, or do:
```
radius: int = 19
```
and then not have it up above
___
*[python/state/ball.py, line 73 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15#-LnilVqK9KK9whpGrH0M:-LnilVqK9KK9whpGrH0N:b-a7sczt) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/6313f2646c102c83643e60325af0fc3de2d251ee/python/state/ball.py#L73)):*
> ```Python
>     def simulate_input(self, keypresses: Keys) -> 'Ball':
>         future_ball = copy.deepcopy(self)
>         self.ax, self.ay = self.accels_from_input(keypresses)
> ```

I think you forgot to update `future_ball` with these inputs.

Also I think a `copy.copy` here is fine (don't need to deepcopy)
___
*[python/state/ball.py, line 98 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15#-Lnild8c2gLsqEn7XFxG:-Lnild8c2gLsqEn7XFxH:b2o2wa8) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/6313f2646c102c83643e60325af0fc3de2d251ee/python/state/ball.py#L98)):*
> ```Python
>         self.x, self.y, self.vx, self.vy = self.simulate_update(dt)
> 
>     def simulate_update(self, dt: int) -> Tuple[float, float, float, float]:
> ```

can you put a `:return` in the docstring?
___
*[python/state/flag.py, line 6 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15#-LnilpXD199-3xZtbvRo:-LnilpXD199-3xZtbvRp:b-bfdjw0) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/6313f2646c102c83643e60325af0fc3de2d251ee/python/state/flag.py#L6)):*
> ```Python
> from visualization.shape import Shape
> 
> radius = 15
> ```

see comment above about `radius`. I'm fine with both approaches (though I think I slightly prefer having the values outside the class, to save space and be clear that they are constants) either way we should be consistentpppppppppppp
___
*[python/state/heuristic_scores.py, line 14 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15#-LnimEc3CxNZfiVTpeGC:-LnimEc3CxNZfiVTpeGD:b-f5gop7) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/6313f2646c102c83643e60325af0fc3de2d251ee/python/state/heuristic_scores.py#L14)):*
> ```Python
>     combined_radius = ego_ball.radius + state.flag.radius
>     flag_ego_sq_dist = math.sq_dist(ego_ball.x, ego_ball.y, state.flag.x, state.flag.y)
>     return max(0, flag_ego_sq_dist - combined_radius)
> ```

is it intentional that we mix pixels^2 and pixels here? (I think thats whats happening)

**Review by altodyte — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15)* status: davidabrahams must resolve 7 discussions (waiting on @altodyte and @davidabrahams)

___
*[python/state/ball.py, line 46 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15#-Lnikyyo-rziCMCKsrE9:-LniriEVBoTmzHz9VMTJ:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/6313f2646c102c83643e60325af0fc3de2d251ee/python/state/ball.py#L46)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

we should have radius stored in one place. My original rational for having it outside the class was that if every ball will always have the exact same radius, we don't need to store it separately for each instance. I think we should either stick to this, or do:
```
radius: int = 19
```
and then not have it up above
</blockquote></details>

Done.
___
*[python/state/ball.py, line 73 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15#-LnilVqK9KK9whpGrH0M:-LnirhvZ4mgioKwZot2l:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/6313f2646c102c83643e60325af0fc3de2d251ee/python/state/ball.py#L73)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

I think you forgot to update `future_ball` with these inputs.

Also I think a `copy.copy` here is fine (don't need to deepcopy)
</blockquote></details>

Done.
___
*[python/state/ball.py, line 98 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15#-Lnild8c2gLsqEn7XFxG:-LnipvWp8ywGYLojW8e2:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/6313f2646c102c83643e60325af0fc3de2d251ee/python/state/ball.py#L98)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

can you put a `:return` in the docstring?
</blockquote></details>

Done.
___
*[python/state/flag.py, line 6 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15#-LnilpXD199-3xZtbvRo:-Lnipebw9XrP-MlzBNrN:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/6313f2646c102c83643e60325af0fc3de2d251ee/python/state/flag.py#L6)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

see comment above about `radius`. I'm fine with both approaches (though I think I slightly prefer having the values outside the class, to save space and be clear that they are constants) either way we should be consistentpppppppppppp
</blockquote></details>

Done.
___
*[python/state/heuristic_scores.py, line 14 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15#-LnimEc3CxNZfiVTpeGC:-Lniotmw4QWn98rWyrsK:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/6313f2646c102c83643e60325af0fc3de2d251ee/python/state/heuristic_scores.py#L14)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

is it intentional that we mix pixels^2 and pixels here? (I think thats whats happening)
</blockquote></details>

Done.

**Review by davidabrahams — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15)* status: davidabrahams must resolve 3 discussions (waiting on @altodyte)

*[a discussion](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15#-LnisPT3053EB4VrN2Sd:-LnisPT3053EB4VrN2Se:b-eqn13c) (no related file):*
travis build failing

also let's run this and make sure it works before merging.

---

**Review by altodyte — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15)* status: davidabrahams must review 3 files, billmwong must review 3 files, shanekelly must review 3 files, davidabrahams must resolve 3 discussions (waiting on @altodyte and @davidabrahams)

___
*[python/main.py, line 41 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15#-LnikDztDpcul-XnFrv7:-LnixO4KAD8sbXA6Uvvx:b-896fix) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/6313f2646c102c83643e60325af0fc3de2d251ee/python/main.py#L41)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

can you comment the high level intent of this block?

```
while space is pressed, we try to random walk to the flag. If randomly generated keypresses are worse than doing nothing, we do nothing.
```
</blockquote></details>

Done.
___
*[python/main.py, line 47 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15#-LnikTDT656hfrL1etpx:-LnixQ4B6jZJumYltL2p:bcte2jx) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/6313f2646c102c83643e60325af0fc3de2d251ee/python/main.py#L47)):*
<details><summary><i>Previously, davidabrahams wrote…</i></summary><blockquote>

we should make a function on `State` which is something like: `def updateBall(ball_id, ball) -> State` so we don't need to deepcopy here
</blockquote></details>

can this be a follow-up? fine if not

**Review by davidabrahams — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15)* status: davidabrahams must resolve 1 discussion (waiting on @altodyte)

___
*[python/main.py, line 47 at r1](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15#-LnikTDT656hfrL1etpx:-Lniz_DN7ZLkvSNLV2Ab:b5ctyo8) ([raw file](https://github.com/chauncy-crib/tagprobot-ml/blob/6313f2646c102c83643e60325af0fc3de2d251ee/python/main.py#L47)):*
<details><summary><i>Previously, altodyte wrote…</i></summary><blockquote>

can this be a follow-up? fine if not
</blockquote></details>

sure. I also think `native_ego_to_flag` should be a function in `State`, but we can do that later.

Can you leave a TODO here?

**Review by davidabrahams — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by davidabrahams — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/chauncy-crib/tagprobot-ml/15)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
